services:
  postgres:
    image: postgres:15
    container_name: monika-notif-engine-postgre
    restart: always
    env_file:
      - packages/env/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
