// This file is automatically generated by [env-to-t3 CLI](https://github.com/nicnocquee/env-to-t3)

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DEBUG: z.string().optional(),
    POSTGRES_USER: z.string().optional(),
    POSTGRES_PASSWORD: z.string().optional(),
    DATABASE_URL: z.string().min(1),
    DATABASE_DIRECT_URL: z.string().min(1),
    FACEBOOK_WEBHOOK_APP_SECRET: z.string().min(1),
    WHATSAPP_API_BASE_URL: z.string().min(1),
    WHATSAPP_API_PHONE_ID: z.string().min(1),
    WHATSAPP_API_ACCESS_TOKEN: z.string().min(1),
    FACEBOOK_WEBHOOK_VERIFY_TOKEN: z.string().min(1),
    NETLIFY_APP_NAME: z.string().optional(),
  },
  client: {
    NEXT_PUBLIC_BASE_URL: z.string().min(1),
    NEXT_PUBLIC_MONIKA_NOTIFY_API_URL: z.string().min(1),
    NEXT_PUBLIC_MONIKA_NOTIF_DOC: z.string().optional(),
    NEXT_PUBLIC_WEBHOOK_RESEND_COOLDOWN_TIME: z.number({ coerce: true }).optional(),
  },
  experimental__runtimeEnv: {
    NEXT_PUBLIC_BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
    NEXT_PUBLIC_MONIKA_NOTIFY_API_URL: process.env.NEXT_PUBLIC_MONIKA_NOTIFY_API_URL,
    NEXT_PUBLIC_MONIKA_NOTIF_DOC: process.env.NEXT_PUBLIC_MONIKA_NOTIF_DOC,
    NEXT_PUBLIC_WEBHOOK_RESEND_COOLDOWN_TIME: process.env.NEXT_PUBLIC_WEBHOOK_RESEND_COOLDOWN_TIME,
  }
});
